"""Seed data derived from the onboarding docs in this workspace."""

DEFAULT_TIMEZONE = "America/New_York"

PHASES = [
    {
        "id": "preboarding",
        "label": "Pre-boarding",
        "window": "Before day 1",
        "summary": "Lock down the basics before the Contractors start date by: Creating Schedule, Preparing Onboarding Buddy, and ensure Core Access has been provided.",
    },
    {
        "id": "week1",
        "label": "Week 1",
        "window": "Days 1-5",
        "summary": "Complete Orientation, tool setup and early shadowing for Student and Employer Support.",
    },
    {
        "id": "student_employer",
        "label": "Student + Employer",
        "window": "Weeks 1-3",
        "summary": "Build product coverage and practice through Lessonly, shadowing, and reverse shadowing.",
    },
    {
        "id": "edu_ramp",
        "label": "EDU Ramp",
        "window": "Weeks 2-5",
        "summary": "Start EDU L1 ticket review and raise confidence with coaching and shadow sessions.",
    },
    {
        "id": "phones",
        "label": "Phone Onboarding",
        "window": "Weeks 6-8",
        "summary": "Ramp onto calls with a phone buddy, call-handling training, and schedule coverage.",
    },
    {
        "id": "wrap_up",
        "label": "Wrap-up",
        "window": "Weeks 8-9",
        "summary": "Close out onboarding, review feedback, and shift into steady-state expectations.",
    },
    {
        "id": "ramp",
        "label": "Month 1-3 Ramp",
        "window": "Months 1-3",
        "summary": "Track performance targets, workflow habits, and conversion readiness.",
    },
]

TASKS = [
    {
        "id": "ctr_confirm_start_details",
        "phase_id": "preboarding",
        "owner_role": "contractor",
        "group": "Readiness",
        "title": "Confirm start date, start time, and time zone",
        "description": "Verify the details from the welcome email before day 1.",
        "due_label": "Before start",
        "dependency_ids": [],
        "source": "contractor-onboarding-guide.md",
    },
    {
        "id": "ctr_prepare_workspace",
        "phase_id": "preboarding",
        "owner_role": "contractor",
        "group": "Readiness",
        "title": "Confirm hardware, workspace, and internet readiness",
        "description": "Make sure the computer setup, quiet workspace, and reliable internet are ready.",
        "due_label": "Before start",
        "dependency_ids": [],
        "source": "contractor-onboarding-guide.md",
    },
    {
        "id": "mgr_add_calendar_invites",
        "phase_id": "preboarding",
        "owner_role": "manager",
        "group": "Scheduling",
        "title": "Add huddles and team calendars",
        "description": "Add the contractor to the EDU Support Huddle, EDU All Hands, and relevant team calendars.",
        "due_label": "Before start",
        "dependency_ids": [],
        "source": "manager-onboarding-checklist.md",
    },
    {
        "id": "mgr_send_welcome_email",
        "phase_id": "preboarding",
        "owner_role": "manager",
        "group": "Communication",
        "title": "Send the welcome email and onboarding doc",
        "description": "Use the standard template and confirm the start date, start time, and time zone.",
        "due_label": "Before start",
        "dependency_ids": [],
        "source": "manager-onboarding-checklist.md",
    },
    {
        "id": "mgr_assign_buddy",
        "phase_id": "preboarding",
        "owner_role": "manager",
        "group": "Support",
        "title": "Assign an onboarding buddy and schedule the first two meetings",
        "description": "Clarify buddy expectations so the contractor knows where to go for help.",
        "due_label": "Before start",
        "dependency_ids": [],
        "source": "manager-onboarding-checklist.md",
    },
    {
        "id": "mgr_request_core_access",
        "phase_id": "preboarding",
        "owner_role": "manager",
        "group": "Access",
        "title": "Request the pre-boarding access bundle",
        "description": "Confirm Workday, Slack, Google Workspace, and Okta baseline apps are requested.",
        "due_label": "Before start",
        "dependency_ids": [],
        "source": "manager-onboarding-checklist.md",
    },
    {
        "id": "ctr_activate_accounts",
        "phase_id": "week1",
        "owner_role": "contractor",
        "group": "Access",
        "title": "Log in to email, Slack, and Okta and enable MFA",
        "description": "Confirm the day-1 account bundle works and report any gaps quickly.",
        "due_label": "Day 1-2",
        "dependency_ids": ["mgr_request_core_access"],
        "source": "contractor-onboarding-guide.md",
    },
    {
        "id": "ctr_complete_orientation_lessonly",
        "phase_id": "week1",
        "owner_role": "contractor",
        "group": "Training",
        "title": "Finish orientation Lessonly courses",
        "description": "Complete Welcome to Handshake, tools overview, Zendesk basics, and customer service foundations.",
        "due_label": "End of week 1",
        "dependency_ids": [],
        "source": "contractor-onboarding-guide.md",
    },
    {
        "id": "ctr_attend_orientation_sessions",
        "phase_id": "week1",
        "owner_role": "contractor",
        "group": "Meetings",
        "title": "Attend the orientation sessions and first buddy meetings",
        "description": "Join the EDU Weekly Huddle, CTR orientation, and early buddy sessions.",
        "due_label": "End of week 1",
        "dependency_ids": ["mgr_add_calendar_invites", "mgr_assign_buddy"],
        "source": "contractor-onboarding-guide.md",
    },
    {
        "id": "ctr_confirm_support_accounts",
        "phase_id": "week1",
        "owner_role": "contractor",
        "group": "Access",
        "title": "Confirm prod and demo accounts plus Zendesk review",
        "description": "Verify all assigned Handshake accounts work and participate in a live Zendesk review.",
        "due_label": "End of week 1",
        "dependency_ids": ["mgr_request_week1_access"],
        "source": "contractor-onboarding-guide.md",
    },
    {
        "id": "mgr_add_slack_channels",
        "phase_id": "week1",
        "owner_role": "manager",
        "group": "Access",
        "title": "Add the contractor to Slack channels and post an intro",
        "description": "Include the onboarding, core team, and help channels the contractor needs right away.",
        "due_label": "Day 1-2",
        "dependency_ids": [],
        "source": "manager-onboarding-checklist.md",
    },
    {
        "id": "mgr_request_week1_access",
        "phase_id": "week1",
        "owner_role": "manager",
        "group": "Access",
        "title": "Request the week-1 tooling bundle",
        "description": "Request prod and demo accounts, Linear, Mailtrap, FullStory, and related support tools.",
        "due_label": "Day 1-2",
        "dependency_ids": [],
        "source": "manager-onboarding-checklist.md",
    },
    {
        "id": "mgr_setup_1on1",
        "phase_id": "week1",
        "owner_role": "manager",
        "group": "Coaching",
        "title": "Create the recurring 1:1 and notes doc",
        "description": "Set up the cadence for feedback, blockers, and ongoing coaching.",
        "due_label": "Day 1-2",
        "dependency_ids": [],
        "source": "manager-onboarding-checklist.md",
    },
    {
        "id": "mgr_validate_week1",
        "phase_id": "week1",
        "owner_role": "manager",
        "group": "Review",
        "title": "Validate week-1 readiness and unblock gaps",
        "description": "Check Lessonly completion, attendance, account access, and align on week-2 focus.",
        "due_label": "End of week 1",
        "dependency_ids": [
            "ctr_complete_orientation_lessonly",
            "ctr_attend_orientation_sessions",
            "ctr_confirm_support_accounts",
        ],
        "source": "manager-onboarding-checklist.md",
    },
    {
        "id": "ctr_complete_student_training",
        "phase_id": "student_employer",
        "owner_role": "contractor",
        "group": "Training",
        "title": "Complete Student support training",
        "description": "Finish Student Product 101, SOPs, Macro Certification, and related Lessonly modules.",
        "due_label": "End of week 2",
        "dependency_ids": [],
        "source": "contractor-onboarding-guide.md",
    },
    {
        "id": "ctr_complete_employer_training",
        "phase_id": "student_employer",
        "owner_role": "contractor",
        "group": "Training",
        "title": "Complete Employer and Premium support training",
        "description": "Finish Employer Product 101, SOPs, premium workflows, and campaign-related modules.",
        "due_label": "End of week 3",
        "dependency_ids": [],
        "source": "contractor-onboarding-guide.md",
    },
    {
        "id": "ctr_shadow_student_and_employer",
        "phase_id": "student_employer",
        "owner_role": "contractor",
        "group": "Shadowing",
        "title": "Join Student and Employer shadow plus reverse-shadow sessions",
        "description": "Observe teammates, handle guided practice, and attend office hours where helpful.",
        "due_label": "Weeks 1-3",
        "dependency_ids": [],
        "source": "contractor-onboarding-guide.md",
    },
    {
        "id": "mgr_align_week2_focus",
        "phase_id": "student_employer",
        "owner_role": "manager",
        "group": "Planning",
        "title": "Align the week-2 and week-3 training focus",
        "description": "Decide whether the contractor should lean Student, Employer, or split focus based on progress.",
        "due_label": "Start of week 2",
        "dependency_ids": ["mgr_validate_week1"],
        "source": "manager-onboarding-checklist.md",
    },
    {
        "id": "ctr_complete_edu_courses",
        "phase_id": "edu_ramp",
        "owner_role": "contractor",
        "group": "Training",
        "title": "Complete EDU Lessonly courses",
        "description": "Finish Intro to EDU and Success, EDU product modules, and EDU Custom Reports.",
        "due_label": "Weeks 2-4",
        "dependency_ids": ["mgr_provision_edu_access"],
        "source": "contractor-onboarding-guide.md",
    },
    {
        "id": "ctr_attend_edu_shadows",
        "phase_id": "edu_ramp",
        "owner_role": "contractor",
        "group": "Shadowing",
        "title": "Attend EDU shadow and reverse-shadow sessions",
        "description": "Join EDU shadow sessions several times per week and use office hours for follow-up questions.",
        "due_label": "Weeks 2-5",
        "dependency_ids": ["mgr_schedule_edu_shadows"],
        "source": "contractor-onboarding-guide.md",
    },
    {
        "id": "ctr_begin_ticket_review",
        "phase_id": "edu_ramp",
        "owner_role": "contractor",
        "group": "Ramp",
        "title": "Begin EDU L1 ticket review work",
        "description": "Start working tickets with the open limit set by the manager and escalate using the documented process.",
        "due_label": "Start of week 2",
        "dependency_ids": ["mgr_provision_edu_access"],
        "source": "contractor-onboarding-guide.md",
    },
    {
        "id": "mgr_provision_edu_access",
        "phase_id": "edu_ramp",
        "owner_role": "manager",
        "group": "Access",
        "title": "Provision the EDU bundle and open limit",
        "description": "Assign EDU courses, request Zendesk and Playvox, add the contractor to EDU L1, and set the open limit to 3.",
        "due_label": "Start of week 2",
        "dependency_ids": [],
        "source": "manager-onboarding-checklist.md",
    },
    {
        "id": "mgr_schedule_edu_shadows",
        "phase_id": "edu_ramp",
        "owner_role": "manager",
        "group": "Shadowing",
        "title": "Schedule EDU shadow and reverse-shadow coverage",
        "description": "Ask EDU seniors to cover week-2 and week-3 sessions and keep the mix balanced.",
        "due_label": "Weeks 2-3",
        "dependency_ids": [],
        "source": "manager-onboarding-checklist.md",
    },
    {
        "id": "mgr_coach_ticket_review",
        "phase_id": "edu_ramp",
        "owner_role": "manager",
        "group": "Coaching",
        "title": "Review ticket quality, QA, and AHT trends",
        "description": "Coach on macros, SOP usage, escalation paths, and increase confidence over time.",
        "due_label": "Weeks 2-5",
        "dependency_ids": ["ctr_begin_ticket_review"],
        "source": "manager-onboarding-checklist.md",
    },
    {
        "id": "ctr_complete_phone_modules",
        "phase_id": "phones",
        "owner_role": "contractor",
        "group": "Training",
        "title": "Finish phone training modules",
        "description": "Complete Phones Overview, Let's Talk Calls, Zendesk Talk, and Phones 101: EDU.",
        "due_label": "End of week 7",
        "dependency_ids": [],
        "source": "contractor-onboarding-guide.md",
    },
    {
        "id": "ctr_complete_phone_shifts",
        "phase_id": "phones",
        "owner_role": "contractor",
        "group": "Shadowing",
        "title": "Complete phone buddy listening and reverse-shadow shifts",
        "description": "Listen to live calls first, then handle voicemails and calls with buddy support.",
        "due_label": "Weeks 6-8",
        "dependency_ids": ["mgr_enable_phone_access"],
        "source": "contractor-onboarding-guide.md",
    },
    {
        "id": "ctr_follow_phone_etiquette",
        "phase_id": "phones",
        "owner_role": "contractor",
        "group": "Operations",
        "title": "Follow phone shift etiquette",
        "description": "Use #support-urgent correctly, avoid taking calls at shift end, and document call coverage clearly.",
        "due_label": "Weeks 6-8",
        "dependency_ids": ["mgr_schedule_phone_ramp"],
        "source": "contractor-onboarding-guide.md",
    },
    {
        "id": "mgr_enable_phone_access",
        "phase_id": "phones",
        "owner_role": "manager",
        "group": "Access",
        "title": "Enable phone permissions and assign the phone buddy",
        "description": "Set up listen, place, and receive permissions and add the contractor to the phone group.",
        "due_label": "Start of week 6",
        "dependency_ids": [],
        "source": "manager-onboarding-checklist.md",
    },
    {
        "id": "mgr_schedule_phone_ramp",
        "phase_id": "phones",
        "owner_role": "manager",
        "group": "Scheduling",
        "title": "Schedule the week-1 and week-2 phone ramp",
        "description": "Plan the listening shifts, reverse-shadow sessions, and initial phone schedule coverage.",
        "due_label": "Weeks 6-8",
        "dependency_ids": ["mgr_enable_phone_access"],
        "source": "manager-onboarding-checklist.md",
    },
    {
        "id": "mgr_reinforce_phone_goals",
        "phase_id": "phones",
        "owner_role": "manager",
        "group": "Coaching",
        "title": "Reinforce phone goals and etiquette",
        "description": "Coach toward 100 percent CSAT, zero missed calls, and proper queue handling norms.",
        "due_label": "Weeks 6-8",
        "dependency_ids": ["ctr_complete_phone_shifts"],
        "source": "manager-onboarding-checklist.md",
    },
    {
        "id": "mgr_scale_open_limit",
        "phase_id": "wrap_up",
        "owner_role": "manager",
        "group": "Ramp",
        "title": "Increase open limit and add on-call coverage",
        "description": "Move the contractor toward the standard EDU L1 open limit and into the on-call rotation.",
        "due_label": "1-2 weeks after phones",
        "dependency_ids": ["ctr_complete_phone_shifts"],
        "source": "manager-onboarding-checklist.md",
    },
    {
        "id": "mgr_review_feedback",
        "phase_id": "wrap_up",
        "owner_role": "manager",
        "group": "Review",
        "title": "Collect feedback from buddy, seniors, and QA",
        "description": "Gather coaching signals from the people who supported the onboarding ramp.",
        "due_label": "1-2 weeks after phones",
        "dependency_ids": [],
        "source": "manager-onboarding-checklist.md",
    },
    {
        "id": "mgr_hold_wrapup",
        "phase_id": "wrap_up",
        "owner_role": "manager",
        "group": "Review",
        "title": "Hold the formal onboarding wrap-up",
        "description": "Share wins, clarify expectations beyond onboarding, and discuss growth areas.",
        "due_label": "1-2 weeks after phones",
        "dependency_ids": ["mgr_review_feedback", "mgr_scale_open_limit"],
        "source": "manager-onboarding-checklist.md",
    },
    {
        "id": "ctr_hit_monthly_targets",
        "phase_id": "ramp",
        "owner_role": "contractor",
        "group": "Performance",
        "title": "Track toward month-by-month ticket and quality targets",
        "description": "Aim for the AHT, CSAT, ticket volume, SLA, and QA targets called out for months 1 through 3.",
        "due_label": "End of month 3",
        "dependency_ids": ["ctr_begin_ticket_review"],
        "source": "contractor-onboarding-guide.md",
    },
    {
        "id": "ctr_maintain_workflow_habits",
        "phase_id": "ramp",
        "owner_role": "contractor",
        "group": "Expectations",
        "title": "Maintain workflow, communication, and schedule expectations",
        "description": "Keep Slack and email responsive, stay aligned to working hours, and follow OOO policy.",
        "due_label": "Months 1-3",
        "dependency_ids": [],
        "source": "contractor-onboarding-guide.md",
    },
    {
        "id": "mgr_review_conversion_readiness",
        "phase_id": "ramp",
        "owner_role": "manager",
        "group": "Performance",
        "title": "Review conversion readiness when headcount is available",
        "description": "Use quantitative metrics and qualitative behaviors to document whether the contractor is ready.",
        "due_label": "End of month 3",
        "dependency_ids": ["mgr_hold_wrapup", "ctr_hit_monthly_targets"],
        "source": "manager-onboarding-checklist.md",
    },
]

ACCESS_BUNDLES = [
    {
        "id": "core_access",
        "phase_id": "preboarding",
        "name": "Core collaboration access",
        "description": "The day-1 collaboration essentials.",
        "items": ["Workday", "Slack", "Google Workspace", "Okta baseline apps"],
    },
    {
        "id": "week1_support_access",
        "phase_id": "week1",
        "name": "Week-1 support tooling",
        "description": "The support systems needed for orientation and early practice.",
        "items": [
            "Prod and demo account bundle",
            "Linear team access",
            "Mailtrap",
            "FullStory",
            "Lessonly",
        ],
    },
    {
        "id": "edu_access",
        "phase_id": "edu_ramp",
        "name": "EDU ticket review bundle",
        "description": "The extra access needed to work EDU L1 safely.",
        "items": ["Zendesk access", "EDU L1 group", "Playvox", "Open limit = 3"],
    },
    {
        "id": "phone_access",
        "phase_id": "phones",
        "name": "Phone coverage bundle",
        "description": "The call handling permissions and schedule access for week 6 onward.",
        "items": ["Zendesk Talk", "Phone queue permissions", "Phone schedule", "#support-urgent workflow"],
    },
    {
        "id": "advanced_reporting",
        "phase_id": "ramp",
        "name": "Advanced reporting access",
        "description": "Looker access once the contractor reaches the right policy gate.",
        "items": ["Looker (L2+ or policy-based)"],
    },
]

METRIC_TARGETS = [
    {
        "month": "Month 1",
        "metrics": [
            {"label": "AHT", "target": "~30 min / ticket"},
            {"label": "CSAT", "target": "85%+"},
            {"label": "Ticket volume", "target": "5-8 weighted tickets / day"},
            {"label": "SLA", "target": "90%"},
            {"label": "QA", "target": "80%+"},
        ],
    },
    {
        "month": "Month 2",
        "metrics": [
            {"label": "AHT", "target": "~20 min / ticket"},
            {"label": "CSAT", "target": "90%+"},
            {"label": "Ticket volume", "target": "8-12 weighted tickets / day"},
            {"label": "SLA", "target": "100%"},
            {"label": "QA", "target": "85%+"},
        ],
    },
    {
        "month": "Month 3",
        "metrics": [
            {"label": "AHT", "target": "~15 min / ticket"},
            {"label": "CSAT", "target": "95%+"},
            {"label": "Ticket volume", "target": "12-15 weighted tickets / day"},
            {"label": "SLA", "target": "100%"},
            {"label": "QA", "target": "90%+"},
        ],
    },
]

PHONE_METRICS = [
    {"label": "Call CSAT", "target": "100%"},
    {"label": "Missed calls", "target": "0"},
    {"label": "Declined calls", "target": "0"},
]

QUALITATIVE_EXPECTATIONS = [
    {
        "category": "Daily workflow",
        "items": [
            "Prioritize Lessonly and onboarding tasks during the ramp.",
            "Work the current onboarding ticket area in the right order: urgent opens, new assignments, then bulk tasks.",
            "Pick up special projects only after onboarding work is covered.",
        ],
    },
    {
        "category": "Communication",
        "items": [
            "Reply to direct Slack messages within about two working hours.",
            "Clear the Handshake inbox at least once per day.",
        ],
    },
    {
        "category": "Schedule",
        "items": [
            "Keep consistent hours, usually 8am-5pm local time.",
            "Stay reachable in Slack and email during working hours.",
            "Keep the calendar accurate and RSVP to events.",
        ],
    },
    {
        "category": "Time off",
        "items": [
            "Follow the internal OOO policy.",
            "Contractors are generally paid only for hours worked.",
            "Follow blackout guidance unless a documented exception applies.",
        ],
    },
]

RESOURCES = [
    {"label": "Ticket Review Process", "category": "Support ops"},
    {"label": "Tech Support Contractor Path", "category": "Career path"},
    {"label": "Handshake and Global Support Values", "category": "Culture"},
    {"label": "AAQ", "category": "Escalation"},
    {"label": "CSAT Workflow", "category": "Quality"},
    {"label": "Ticket Status", "category": "Support ops"},
    {"label": "Internal Notes", "category": "Support ops"},
    {"label": "CoffeeHR Timesheets", "category": "Admin"},
    {"label": "CoffeeHR Benefits", "category": "Admin"},
    {"label": "Workday Onboarding Checklist", "category": "Admin"},
]

DEMO_MANAGER_EMAIL = "ashley.manager@demo.handshake"
DEMO_CONTRACTOR_EMAILS = ["jamie.contractor@demo.handshake", "sam.contractor@demo.handshake"]

DEMO_HINTS = [
    {"role": "contractor", "label": "Contractor test account", "viewer_email": "jamie.contractor@demo.handshake", "contractor_email": "jamie.contractor@demo.handshake"},
    {"role": "contractor", "label": "Second contractor test account", "viewer_email": "sam.contractor@demo.handshake", "contractor_email": "sam.contractor@demo.handshake"},
    {"role": "manager", "label": "Manager test account", "viewer_email": "ashley.manager@demo.handshake", "contractor_email": "jamie.contractor@demo.handshake"},
]

ACCESS_STATUSES = ["not_requested", "requested", "granted", "blocked"]
